Remove dockerfilelint-precommit-hooks
This hook hasn't been updated since 2018, we don't really use the
Dockerfiles any more, and it throws the following error on rolling /
kilted / Ubuntu 2024.04:

    [INFO] Installing environment for https://github.com/pryorda/dockerfilelint-precommit-hooks.
    [INFO] Once installed this environment will be reused.
    [INFO] This may take a few minutes...
    An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3', '-mnodeenv', '--prebuilt', '--clean-src', '/github/home/.cache/pre-commit/repo13yssmlf/node_env-default')
    return code: 1
    stdout: (none)
    stderr:
        /usr/lib/python3/dist-packages/nodeenv.py:24: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
          import pipes
        /usr/lib/python3/dist-packages/nodeenv.py:37: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
          from pkg_resources import parse_version
        Traceback (most recent call last):
          File "<frozen runpy>", line 198, in _run_module_as_main
          File "<frozen runpy>", line 88, in _run_code
          File "/usr/lib/python3/dist-packages/nodeenv.py", line 1042, in <module>
            main()
          File "/usr/lib/python3/dist-packages/nodeenv.py", line 881, in main
            opt.node = get_last_stable_node_version()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/usr/lib/python3/dist-packages/nodeenv.py", line 835, in get_last_stable_node_version
            return links[-1][0]
                   ~~~~~^^^^
        IndexError: list index out of range
    Check the log at /github/home/.cache/pre-commit/pre-commit.log